### ISSUE TITLE
Accept children on ReflexSplitter

### ISSUE THREAD

**Issue by smeijer** [leefsmp/Re-Flex#25]
Please accept `children` on `ReflexSplitter`. In my case; I wan't to add an icon when the user hovers the splitter. When accepting children, this can easily be done with:

```jsx
<ReflexSplitter>
  <MyIcon className="icon" />
</ReflexSplitter>
```
```css
.reflex-splitter .icon {
  opacity: 0;
}

.reflex-splitter:hover .icon {
  opacity: 1;
}
```
